// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QA.DataAccess;

#nullable disable

namespace QA.DataAccess.Migrations
{
    [DbContext(typeof(QAContext))]
    [Migration("20240725063239_OpearationDetailsPrecision")]
    partial class OpearationDetailsPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QA.Domain.Models.ChildParametersAssignement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChildParameterId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentParameterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildParameterId");

                    b.HasIndex("ParentParameterId");

                    b.ToTable("ChildParametersAssignement");
                });

            modelBuilder.Entity("QA.Domain.Models.Defect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DefectCategoryId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("QA.Domain.Models.DefectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DefectCategories");
                });

            modelBuilder.Entity("QA.Domain.Models.DevicePort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasuringDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MeasuringDeviceId");

                    b.ToTable("DevicePorts");
                });

            modelBuilder.Entity("QA.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId")
                        .IsUnique()
                        .HasFilter("[ParameterId] IS NOT NULL");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("QA.Domain.Models.Keyence.KeyenceMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FileModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.ToTable("KeyenceMeasurements");
                });

            modelBuilder.Entity("QA.Domain.Models.Keyence.KeyenceParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("LSL")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("LowerTollerance")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Number")
                        .HasPrecision(3, 1)
                        .HasColumnType("int");

                    b.Property<decimal>("USL")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UpperTollerance")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("Id");

                    b.ToTable("KeyenceParameters");
                });

            modelBuilder.Entity("QA.Domain.Models.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VisualInspectionFormId")
                        .HasColumnType("int");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("VisualInspectionFormId");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("QA.Domain.Models.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("EdgeNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsControllerMeasuremnt")
                        .HasColumnType("bit");

                    b.Property<int?>("MeasurementSeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Operator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderKey")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementSeriesId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ParameterId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("QA.Domain.Models.MeasurementsSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PositionOnTray")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<string>("TrayNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("OrderId");

                    b.ToTable("MeasurementsSeries");
                });

            modelBuilder.Entity("QA.Domain.Models.MeasuringDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MeasuringDevices");
                });

            modelBuilder.Entity("QA.Domain.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("QA.Domain.Models.OperationDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BurrRate")
                        .HasColumnType("int");

                    b.Property<int?>("Feed")
                        .HasColumnType("int");

                    b.Property<decimal?>("GunsPitch")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int?>("HeadsQty")
                        .HasMaxLength(150)
                        .HasColumnType("int");

                    b.Property<string>("NoBlastingBetweenRows")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfPasses")
                        .HasColumnType("int");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<decimal?>("PressureLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PressureRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProcessTray")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Program")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SandblastingHeight")
                        .HasColumnType("int");

                    b.Property<string>("ScanningMode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationDetails");
                });

            modelBuilder.Entity("QA.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HermesId")
                        .HasColumnType("int");

                    b.Property<string>("OrderKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowDatetime")
                        .HasColumnType("datetime");

                    b.Property<string>("ShortenedKey")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("VisualInspectionFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VisualInspectionFormId")
                        .IsUnique()
                        .HasFilter("[VisualInspectionFormId] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QA.Domain.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticMeasurement")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("DevicePortId")
                        .HasColumnType("int");

                    b.Property<int?>("EdgesQty")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChildParameter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrialParameter")
                        .HasColumnType("bit");

                    b.Property<decimal>("LSL")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("LowerTolerance")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NominalValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterType")
                        .HasColumnType("int");

                    b.Property<string>("SampleClass")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("USL")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UpperTolerance")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("DevicePortId");

                    b.HasIndex("OperationId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("QA.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("InstructionPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPattern")
                        .HasColumnType("bit");

                    b.Property<string>("PdmNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("QA.Domain.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("DefectsQty")
                        .HasColumnType("int");

                    b.Property<int?>("GoodsQty")
                        .HasColumnType("int");

                    b.Property<string>("Operator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SampleNumber")
                        .HasColumnType("int");

                    b.Property<int>("SampleQty")
                        .HasColumnType("int");

                    b.Property<int>("VisualInspectionFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisualInspectionFormId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("QA.Domain.Models.SampleDefect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectId")
                        .HasColumnType("int");

                    b.Property<string>("DefectSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("DefectsQty")
                        .HasColumnType("int");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.HasIndex("SampleId");

                    b.ToTable("SampleDefects");
                });

            modelBuilder.Entity("QA.Domain.Models.VisualInspectionForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("InstructionNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("KeyenceIsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("MRBNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("VisualInspectionForms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QA.Domain.Models.ChildParametersAssignement", b =>
                {
                    b.HasOne("QA.Domain.Models.Parameter", "ChildParameter")
                        .WithMany()
                        .HasForeignKey("ChildParameterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QA.Domain.Models.Parameter", "ParentParameter")
                        .WithMany("ChildParametersAssignements")
                        .HasForeignKey("ParentParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChildParameter");

                    b.Navigation("ParentParameter");
                });

            modelBuilder.Entity("QA.Domain.Models.Defect", b =>
                {
                    b.HasOne("QA.Domain.Models.DefectCategory", "DefectCategory")
                        .WithMany("Defects")
                        .HasForeignKey("DefectCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectCategory");
                });

            modelBuilder.Entity("QA.Domain.Models.DevicePort", b =>
                {
                    b.HasOne("QA.Domain.Models.MeasuringDevice", "MeasuringDevice")
                        .WithMany("Ports")
                        .HasForeignKey("MeasuringDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasuringDevice");
                });

            modelBuilder.Entity("QA.Domain.Models.Image", b =>
                {
                    b.HasOne("QA.Domain.Models.Parameter", "Parameter")
                        .WithOne("Image")
                        .HasForeignKey("QA.Domain.Models.Image", "ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QA.Domain.Models.Product", "Product")
                        .WithOne("Image")
                        .HasForeignKey("QA.Domain.Models.Image", "ProductId");

                    b.Navigation("Parameter");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QA.Domain.Models.Keyence.KeyenceMeasurement", b =>
                {
                    b.HasOne("QA.Domain.Models.Keyence.KeyenceParameter", "Parameter")
                        .WithMany("Measurements")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("QA.Domain.Models.Marker", b =>
                {
                    b.HasOne("QA.Domain.Models.VisualInspectionForm", "VisualInspectionForm")
                        .WithMany("Markers")
                        .HasForeignKey("VisualInspectionFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisualInspectionForm");
                });

            modelBuilder.Entity("QA.Domain.Models.Measurement", b =>
                {
                    b.HasOne("QA.Domain.Models.MeasurementsSeries", "MeasurementsSeries")
                        .WithMany("Measurements")
                        .HasForeignKey("MeasurementSeriesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QA.Domain.Models.Order", "Order")
                        .WithMany("Measurements")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QA.Domain.Models.Parameter", "Parameter")
                        .WithMany("Measurements")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementsSeries");

                    b.Navigation("Order");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("QA.Domain.Models.MeasurementsSeries", b =>
                {
                    b.HasOne("QA.Domain.Models.Operation", "Operation")
                        .WithMany("MeasurementsSeries")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QA.Domain.Models.Order", "Order")
                        .WithMany("MeasurementsSeries")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QA.Domain.Models.Operation", b =>
                {
                    b.HasOne("QA.Domain.Models.Product", "Product")
                        .WithMany("Operations")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QA.Domain.Models.OperationDetails", b =>
                {
                    b.HasOne("QA.Domain.Models.Operation", "Operation")
                        .WithMany("OperationDetails")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("QA.Domain.Models.Order", b =>
                {
                    b.HasOne("QA.Domain.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QA.Domain.Models.VisualInspectionForm", "VisualInspectionForm")
                        .WithOne("Order")
                        .HasForeignKey("QA.Domain.Models.Order", "VisualInspectionFormId");

                    b.Navigation("Product");

                    b.Navigation("VisualInspectionForm");
                });

            modelBuilder.Entity("QA.Domain.Models.Parameter", b =>
                {
                    b.HasOne("QA.Domain.Models.DevicePort", "DevicePort")
                        .WithMany("Parameters")
                        .HasForeignKey("DevicePortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QA.Domain.Models.Operation", "Operation")
                        .WithMany("Parameters")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevicePort");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("QA.Domain.Models.Sample", b =>
                {
                    b.HasOne("QA.Domain.Models.VisualInspectionForm", "VisualInspectionForm")
                        .WithMany("Samples")
                        .HasForeignKey("VisualInspectionFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisualInspectionForm");
                });

            modelBuilder.Entity("QA.Domain.Models.SampleDefect", b =>
                {
                    b.HasOne("QA.Domain.Models.Defect", "Defect")
                        .WithMany()
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QA.Domain.Models.Sample", "Sample")
                        .WithMany("SampleDefects")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defect");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("QA.Domain.Models.VisualInspectionForm", b =>
                {
                    b.HasOne("QA.Domain.Models.Image", "Image")
                        .WithMany("VisualInspectionForms")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("QA.Domain.Models.DefectCategory", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("QA.Domain.Models.DevicePort", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("QA.Domain.Models.Image", b =>
                {
                    b.Navigation("VisualInspectionForms");
                });

            modelBuilder.Entity("QA.Domain.Models.Keyence.KeyenceParameter", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("QA.Domain.Models.MeasurementsSeries", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("QA.Domain.Models.MeasuringDevice", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("QA.Domain.Models.Operation", b =>
                {
                    b.Navigation("MeasurementsSeries");

                    b.Navigation("OperationDetails");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("QA.Domain.Models.Order", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("MeasurementsSeries");
                });

            modelBuilder.Entity("QA.Domain.Models.Parameter", b =>
                {
                    b.Navigation("ChildParametersAssignements");

                    b.Navigation("Image");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("QA.Domain.Models.Product", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Operations");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QA.Domain.Models.Sample", b =>
                {
                    b.Navigation("SampleDefects");
                });

            modelBuilder.Entity("QA.Domain.Models.VisualInspectionForm", b =>
                {
                    b.Navigation("Markers");

                    b.Navigation("Order")
                        .IsRequired();

                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
